version: "3"

services:
  web:
    build: ./web
    image: lemonrhum/flask-redis:1.0
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    ports: ['5000:5000']
    volumes: ['./web:/app']

  redis:
    image: redis:4.0.11-alpine